config_ordinal: 150
server.url: http://localhost:7001
web-api/mp-rest/url: ${server.url}
main.manifest.jar: msa-rms-ui-console\.jar$

configuredCdi:
  register:
    - class: io.extact.msa.rms.platform.fw.external.PropagateJwtClientHeadersFactory
