config_ordinal: 150
#----------------------------------
# Defined for each environment
#----------------------------------
env.rms:
  server.url: http://localhost:7001

#----------------------------------
# Helidon Configurations
#----------------------------------
web-api/mp-rest/url: ${env.rms.server.url}

#----------------------------------
# Applications Configurations
#----------------------------------
rms:
  cdi:
    configuredCdi:
      register:
        - class: io.extact.msa.rms.platform.fw.external.PropagateJwtClientHeadersFactory
  env:
    main.jar: msa-rms-ui-console\.jar$
